# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from boat.v1 import backbone_pb2 as boat_dot_v1_dot_backbone__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in boat/v1/backbone_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BackboneServiceStub:
    """BackboneService — bidirectional streaming between gateway peers.
    Each gateway connects to every peer; both sides send and receive
    BackboneFrame messages on the same stream. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/boat.v1.BackboneService/Connect',
                request_serializer=boat_dot_v1_dot_backbone__pb2.BackboneFrame.SerializeToString,
                response_deserializer=boat_dot_v1_dot_backbone__pb2.BackboneFrame.FromString,
                _registered_method=True)


class BackboneServiceServicer:
    """BackboneService — bidirectional streaming between gateway peers.
    Each gateway connects to every peer; both sides send and receive
    BackboneFrame messages on the same stream. 
    """

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BackboneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=boat_dot_v1_dot_backbone__pb2.BackboneFrame.FromString,
                    response_serializer=boat_dot_v1_dot_backbone__pb2.BackboneFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boat.v1.BackboneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('boat.v1.BackboneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BackboneService:
    """BackboneService — bidirectional streaming between gateway peers.
    Each gateway connects to every peer; both sides send and receive
    BackboneFrame messages on the same stream. 
    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/boat.v1.BackboneService/Connect',
            boat_dot_v1_dot_backbone__pb2.BackboneFrame.SerializeToString,
            boat_dot_v1_dot_backbone__pb2.BackboneFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
