# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: boat/v1/backbone.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'boat/v1/backbone.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from boat.v1 import frame_pb2 as boat_dot_v1_dot_frame__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x62oat/v1/backbone.proto\x12\x07\x62oat.v1\x1a\x13\x62oat/v1/frame.proto\"u\n\rBackboneFrame\x12\x19\n\x11origin_gateway_id\x18\x01 \x01(\t\x12\x11\n\thop_count\x18\x02 \x01(\r\x12\x17\n\x0fsequence_number\x18\x03 \x01(\x04\x12\x1d\n\x05\x66rame\x18\x04 \x01(\x0b\x32\x0e.boat.v1.Frame2P\n\x0f\x42\x61\x63kboneService\x12=\n\x07\x43onnect\x12\x16.boat.v1.BackboneFrame\x1a\x16.boat.v1.BackboneFrame(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'boat.v1.backbone_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BACKBONEFRAME']._serialized_start=56
  _globals['_BACKBONEFRAME']._serialized_end=173
  _globals['_BACKBONESERVICE']._serialized_start=175
  _globals['_BACKBONESERVICE']._serialized_end=255
# @@protoc_insertion_point(module_scope)
