# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from boat.v1 import can_pb2 as boat_dot_v1_dot_can__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in boat/v1/can_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CanServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCanFrame = channel.unary_unary(
                '/boat.v1.CanService/SendCanFrame',
                request_serializer=boat_dot_v1_dot_can__pb2.SendCanFrameRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_can__pb2.SendCanFrameResponse.FromString,
                _registered_method=True)
        self.SubscribeCanFrames = channel.unary_stream(
                '/boat.v1.CanService/SubscribeCanFrames',
                request_serializer=boat_dot_v1_dot_can__pb2.SubscribeCanFramesRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_can__pb2.CanFrame.FromString,
                _registered_method=True)
        self.ListBuses = channel.unary_unary(
                '/boat.v1.CanService/ListBuses',
                request_serializer=boat_dot_v1_dot_can__pb2.ListBusesRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_can__pb2.ListBusesResponse.FromString,
                _registered_method=True)


class CanServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SendCanFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeCanFrames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBuses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCanFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCanFrame,
                    request_deserializer=boat_dot_v1_dot_can__pb2.SendCanFrameRequest.FromString,
                    response_serializer=boat_dot_v1_dot_can__pb2.SendCanFrameResponse.SerializeToString,
            ),
            'SubscribeCanFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeCanFrames,
                    request_deserializer=boat_dot_v1_dot_can__pb2.SubscribeCanFramesRequest.FromString,
                    response_serializer=boat_dot_v1_dot_can__pb2.CanFrame.SerializeToString,
            ),
            'ListBuses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBuses,
                    request_deserializer=boat_dot_v1_dot_can__pb2.ListBusesRequest.FromString,
                    response_serializer=boat_dot_v1_dot_can__pb2.ListBusesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boat.v1.CanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('boat.v1.CanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CanService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendCanFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.CanService/SendCanFrame',
            boat_dot_v1_dot_can__pb2.SendCanFrameRequest.SerializeToString,
            boat_dot_v1_dot_can__pb2.SendCanFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeCanFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/boat.v1.CanService/SubscribeCanFrames',
            boat_dot_v1_dot_can__pb2.SubscribeCanFramesRequest.SerializeToString,
            boat_dot_v1_dot_can__pb2.CanFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBuses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.CanService/ListBuses',
            boat_dot_v1_dot_can__pb2.ListBusesRequest.SerializeToString,
            boat_dot_v1_dot_can__pb2.ListBusesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
