# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: boat/v1/common.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'boat/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62oat/v1/common.proto\x12\x07\x62oat.v1\":\n\x11PaginationRequest\x12\x11\n\tpage_size\x18\x01 \x01(\r\x12\x12\n\npage_token\x18\x02 \x01(\t\"A\n\x12PaginationResponse\x12\x17\n\x0fnext_page_token\x18\x01 \x01(\t\x12\x12\n\ntotal_size\x18\x02 \x01(\r\"\x93\x01\n\x0b\x45rrorDetail\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x34\n\x08metadata\x18\x03 \x03(\x0b\x32\".boat.v1.ErrorDetail.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\xc3\x01\n\x0fSimulationState\x12 \n\x1cSIMULATION_STATE_UNSPECIFIED\x10\x00\x12\x19\n\x15SIMULATION_STATE_IDLE\x10\x01\x12\x1c\n\x18SIMULATION_STATE_RUNNING\x10\x02\x12\x1b\n\x17SIMULATION_STATE_PAUSED\x10\x03\x12\x1c\n\x18SIMULATION_STATE_STOPPED\x10\x04\x12\x1a\n\x16SIMULATION_STATE_ERROR\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'boat.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERRORDETAIL_METADATAENTRY']._loaded_options = None
  _globals['_ERRORDETAIL_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SIMULATIONSTATE']._serialized_start=311
  _globals['_SIMULATIONSTATE']._serialized_end=506
  _globals['_PAGINATIONREQUEST']._serialized_start=33
  _globals['_PAGINATIONREQUEST']._serialized_end=91
  _globals['_PAGINATIONRESPONSE']._serialized_start=93
  _globals['_PAGINATIONRESPONSE']._serialized_end=158
  _globals['_ERRORDETAIL']._serialized_start=161
  _globals['_ERRORDETAIL']._serialized_end=308
  _globals['_ERRORDETAIL_METADATAENTRY']._serialized_start=261
  _globals['_ERRORDETAIL_METADATAENTRY']._serialized_end=308
# @@protoc_insertion_point(module_scope)
