# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from boat.v1 import device_pb2 as boat_dot_v1_dot_device__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in boat/v1/device_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDevices = channel.unary_unary(
                '/boat.v1.DeviceService/ListDevices',
                request_serializer=boat_dot_v1_dot_device__pb2.ListDevicesRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_device__pb2.ListDevicesResponse.FromString,
                _registered_method=True)
        self.SetControl = channel.unary_unary(
                '/boat.v1.DeviceService/SetControl',
                request_serializer=boat_dot_v1_dot_device__pb2.SetControlRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_device__pb2.SetControlResponse.FromString,
                _registered_method=True)
        self.ReadState = channel.unary_unary(
                '/boat.v1.DeviceService/ReadState',
                request_serializer=boat_dot_v1_dot_device__pb2.ReadStateRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_device__pb2.ReadStateResponse.FromString,
                _registered_method=True)
        self.StreamState = channel.unary_stream(
                '/boat.v1.DeviceService/StreamState',
                request_serializer=boat_dot_v1_dot_device__pb2.StreamStateRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_device__pb2.DeviceStateUpdate.FromString,
                _registered_method=True)


class DeviceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=boat_dot_v1_dot_device__pb2.ListDevicesRequest.FromString,
                    response_serializer=boat_dot_v1_dot_device__pb2.ListDevicesResponse.SerializeToString,
            ),
            'SetControl': grpc.unary_unary_rpc_method_handler(
                    servicer.SetControl,
                    request_deserializer=boat_dot_v1_dot_device__pb2.SetControlRequest.FromString,
                    response_serializer=boat_dot_v1_dot_device__pb2.SetControlResponse.SerializeToString,
            ),
            'ReadState': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadState,
                    request_deserializer=boat_dot_v1_dot_device__pb2.ReadStateRequest.FromString,
                    response_serializer=boat_dot_v1_dot_device__pb2.ReadStateResponse.SerializeToString,
            ),
            'StreamState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamState,
                    request_deserializer=boat_dot_v1_dot_device__pb2.StreamStateRequest.FromString,
                    response_serializer=boat_dot_v1_dot_device__pb2.DeviceStateUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boat.v1.DeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('boat.v1.DeviceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.DeviceService/ListDevices',
            boat_dot_v1_dot_device__pb2.ListDevicesRequest.SerializeToString,
            boat_dot_v1_dot_device__pb2.ListDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.DeviceService/SetControl',
            boat_dot_v1_dot_device__pb2.SetControlRequest.SerializeToString,
            boat_dot_v1_dot_device__pb2.SetControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.DeviceService/ReadState',
            boat_dot_v1_dot_device__pb2.ReadStateRequest.SerializeToString,
            boat_dot_v1_dot_device__pb2.ReadStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/boat.v1.DeviceService/StreamState',
            boat_dot_v1_dot_device__pb2.StreamStateRequest.SerializeToString,
            boat_dot_v1_dot_device__pb2.DeviceStateUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
