# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: boat/v1/ethernet.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'boat/v1/ethernet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x62oat/v1/ethernet.proto\x12\x07\x62oat.v1\"\xbd\x01\n\rEthernetFrame\x12\r\n\x05iface\x18\x01 \x01(\t\x12\x0f\n\x07src_mac\x18\x02 \x01(\x0c\x12\x0f\n\x07\x64st_mac\x18\x03 \x01(\x0c\x12\x11\n\tethertype\x18\x04 \x01(\r\x12\x0f\n\x07payload\x18\x05 \x01(\x0c\x12\x14\n\x0ctimestamp_ns\x18\x06 \x01(\x04\x12\x0f\n\x07vlan_id\x18\x07 \x01(\r\x12\x10\n\x08vlan_pcp\x18\x08 \x01(\r\x12\x0e\n\x06src_ip\x18\t \x01(\x0c\x12\x0e\n\x06\x64st_ip\x18\n \x01(\x0c\"A\n\x18SendEthernetFrameRequest\x12%\n\x05\x66rame\x18\x01 \x01(\x0b\x32\x16.boat.v1.EthernetFrame\"-\n\x19SendEthernetFrameResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\"B\n\x1eSubscribeEthernetFramesRequest\x12\r\n\x05iface\x18\x01 \x01(\t\x12\x11\n\tethertype\x18\x02 \x01(\r\"\x1f\n\x1dListEthernetInterfacesRequest\"0\n\x1eListEthernetInterfacesResponse\x12\x0e\n\x06ifaces\x18\x01 \x03(\t2\x9e\x02\n\x0f\x45thernetService\x12R\n\tSendFrame\x12!.boat.v1.SendEthernetFrameRequest\x1a\".boat.v1.SendEthernetFrameResponse\x12T\n\x0fSubscribeFrames\x12\'.boat.v1.SubscribeEthernetFramesRequest\x1a\x16.boat.v1.EthernetFrame0\x01\x12\x61\n\x0eListInterfaces\x12&.boat.v1.ListEthernetInterfacesRequest\x1a\'.boat.v1.ListEthernetInterfacesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'boat.v1.ethernet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ETHERNETFRAME']._serialized_start=36
  _globals['_ETHERNETFRAME']._serialized_end=225
  _globals['_SENDETHERNETFRAMEREQUEST']._serialized_start=227
  _globals['_SENDETHERNETFRAMEREQUEST']._serialized_end=292
  _globals['_SENDETHERNETFRAMERESPONSE']._serialized_start=294
  _globals['_SENDETHERNETFRAMERESPONSE']._serialized_end=339
  _globals['_SUBSCRIBEETHERNETFRAMESREQUEST']._serialized_start=341
  _globals['_SUBSCRIBEETHERNETFRAMESREQUEST']._serialized_end=407
  _globals['_LISTETHERNETINTERFACESREQUEST']._serialized_start=409
  _globals['_LISTETHERNETINTERFACESREQUEST']._serialized_end=440
  _globals['_LISTETHERNETINTERFACESRESPONSE']._serialized_start=442
  _globals['_LISTETHERNETINTERFACESRESPONSE']._serialized_end=490
  _globals['_ETHERNETSERVICE']._serialized_start=493
  _globals['_ETHERNETSERVICE']._serialized_end=779
# @@protoc_insertion_point(module_scope)
