# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from boat.v1 import fault_pb2 as boat_dot_v1_dot_fault__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in boat/v1/fault_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FaultServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InjectFault = channel.unary_unary(
                '/boat.v1.FaultService/InjectFault',
                request_serializer=boat_dot_v1_dot_fault__pb2.InjectFaultRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_fault__pb2.InjectFaultResponse.FromString,
                _registered_method=True)
        self.ListFaults = channel.unary_unary(
                '/boat.v1.FaultService/ListFaults',
                request_serializer=boat_dot_v1_dot_fault__pb2.ListFaultsRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_fault__pb2.ListFaultsResponse.FromString,
                _registered_method=True)


class FaultServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def InjectFault(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFaults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaultServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InjectFault': grpc.unary_unary_rpc_method_handler(
                    servicer.InjectFault,
                    request_deserializer=boat_dot_v1_dot_fault__pb2.InjectFaultRequest.FromString,
                    response_serializer=boat_dot_v1_dot_fault__pb2.InjectFaultResponse.SerializeToString,
            ),
            'ListFaults': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFaults,
                    request_deserializer=boat_dot_v1_dot_fault__pb2.ListFaultsRequest.FromString,
                    response_serializer=boat_dot_v1_dot_fault__pb2.ListFaultsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boat.v1.FaultService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('boat.v1.FaultService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FaultService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InjectFault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.FaultService/InjectFault',
            boat_dot_v1_dot_fault__pb2.InjectFaultRequest.SerializeToString,
            boat_dot_v1_dot_fault__pb2.InjectFaultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFaults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.FaultService/ListFaults',
            boat_dot_v1_dot_fault__pb2.ListFaultsRequest.SerializeToString,
            boat_dot_v1_dot_fault__pb2.ListFaultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
