# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: boat/v1/fault.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'boat/v1/fault.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from boat.v1 import common_pb2 as boat_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62oat/v1/fault.proto\x12\x07\x62oat.v1\x1a\x14\x62oat/v1/common.proto\"k\n\x12InjectFaultRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\x12 \n\x04type\x18\x03 \x01(\x0e\x32\x12.boat.v1.FaultType\x12\x0c\n\x04tick\x18\x04 \x01(\x04\"T\n\x11ListFaultsRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\x12(\n\x04page\x18\x02 \x01(\x0b\x32\x1a.boat.v1.PaginationRequest\"u\n\nFaultEvent\x12\x10\n\x08\x66\x61ult_id\x18\x01 \x01(\t\x12\x15\n\rsimulation_id\x18\x02 \x01(\t\x12\x0e\n\x06target\x18\x03 \x01(\t\x12 \n\x04type\x18\x04 \x01(\x0e\x32\x12.boat.v1.FaultType\x12\x0c\n\x04tick\x18\x05 \x01(\x04\"^\n\x13InjectFaultResponse\x12\"\n\x05\x66\x61ult\x18\x01 \x01(\x0b\x32\x13.boat.v1.FaultEvent\x12#\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x14.boat.v1.ErrorDetail\"d\n\x12ListFaultsResponse\x12#\n\x06\x66\x61ults\x18\x01 \x03(\x0b\x32\x13.boat.v1.FaultEvent\x12)\n\x04page\x18\x02 \x01(\x0b\x32\x1b.boat.v1.PaginationResponse*{\n\tFaultType\x12\x1a\n\x16\x46\x41ULT_TYPE_UNSPECIFIED\x10\x00\x12 \n\x1c\x46\x41ULT_TYPE_SIGNAL_CORRUPTION\x10\x01\x12\x1a\n\x16\x46\x41ULT_TYPE_PACKET_DROP\x10\x02\x12\x14\n\x10\x46\x41ULT_TYPE_DELAY\x10\x03\x32\x9f\x01\n\x0c\x46\x61ultService\x12H\n\x0bInjectFault\x12\x1b.boat.v1.InjectFaultRequest\x1a\x1c.boat.v1.InjectFaultResponse\x12\x45\n\nListFaults\x12\x1a.boat.v1.ListFaultsRequest\x1a\x1b.boat.v1.ListFaultsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'boat.v1.fault_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FAULTTYPE']._serialized_start=566
  _globals['_FAULTTYPE']._serialized_end=689
  _globals['_INJECTFAULTREQUEST']._serialized_start=54
  _globals['_INJECTFAULTREQUEST']._serialized_end=161
  _globals['_LISTFAULTSREQUEST']._serialized_start=163
  _globals['_LISTFAULTSREQUEST']._serialized_end=247
  _globals['_FAULTEVENT']._serialized_start=249
  _globals['_FAULTEVENT']._serialized_end=366
  _globals['_INJECTFAULTRESPONSE']._serialized_start=368
  _globals['_INJECTFAULTRESPONSE']._serialized_end=462
  _globals['_LISTFAULTSRESPONSE']._serialized_start=464
  _globals['_LISTFAULTSRESPONSE']._serialized_end=564
  _globals['_FAULTSERVICE']._serialized_start=692
  _globals['_FAULTSERVICE']._serialized_end=851
# @@protoc_insertion_point(module_scope)
