# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from boat.v1 import frame_pb2 as boat_dot_v1_dot_frame__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in boat/v1/frame_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FrameServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendFrame = channel.unary_unary(
                '/boat.v1.FrameService/SendFrame',
                request_serializer=boat_dot_v1_dot_frame__pb2.SendFrameRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_frame__pb2.SendFrameResponse.FromString,
                _registered_method=True)
        self.SubscribeFrames = channel.unary_stream(
                '/boat.v1.FrameService/SubscribeFrames',
                request_serializer=boat_dot_v1_dot_frame__pb2.SubscribeFramesRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_frame__pb2.Frame.FromString,
                _registered_method=True)


class FrameServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SendFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeFrames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFrame,
                    request_deserializer=boat_dot_v1_dot_frame__pb2.SendFrameRequest.FromString,
                    response_serializer=boat_dot_v1_dot_frame__pb2.SendFrameResponse.SerializeToString,
            ),
            'SubscribeFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeFrames,
                    request_deserializer=boat_dot_v1_dot_frame__pb2.SubscribeFramesRequest.FromString,
                    response_serializer=boat_dot_v1_dot_frame__pb2.Frame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boat.v1.FrameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('boat.v1.FrameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FrameService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.FrameService/SendFrame',
            boat_dot_v1_dot_frame__pb2.SendFrameRequest.SerializeToString,
            boat_dot_v1_dot_frame__pb2.SendFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/boat.v1.FrameService/SubscribeFrames',
            boat_dot_v1_dot_frame__pb2.SubscribeFramesRequest.SerializeToString,
            boat_dot_v1_dot_frame__pb2.Frame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
