# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: boat/v1/metrics.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'boat/v1/metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62oat/v1/metrics.proto\x12\x07\x62oat.v1\"*\n\x11GetMetricsRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\"-\n\x14StreamMetricsRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\"8\n\x0bMetricPoint\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x0c\n\x04tick\x18\x03 \x01(\x04\"7\n\x0fMetricsResponse\x12$\n\x06points\x18\x01 \x03(\x0b\x32\x14.boat.v1.MetricPoint2\x9c\x01\n\x0eMetricsService\x12\x42\n\nGetMetrics\x12\x1a.boat.v1.GetMetricsRequest\x1a\x18.boat.v1.MetricsResponse\x12\x46\n\rStreamMetrics\x12\x1d.boat.v1.StreamMetricsRequest\x1a\x14.boat.v1.MetricPoint0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'boat.v1.metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETMETRICSREQUEST']._serialized_start=34
  _globals['_GETMETRICSREQUEST']._serialized_end=76
  _globals['_STREAMMETRICSREQUEST']._serialized_start=78
  _globals['_STREAMMETRICSREQUEST']._serialized_end=123
  _globals['_METRICPOINT']._serialized_start=125
  _globals['_METRICPOINT']._serialized_end=181
  _globals['_METRICSRESPONSE']._serialized_start=183
  _globals['_METRICSRESPONSE']._serialized_end=238
  _globals['_METRICSSERVICE']._serialized_start=241
  _globals['_METRICSSERVICE']._serialized_end=397
# @@protoc_insertion_point(module_scope)
