# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from boat.v1 import pdu_pb2 as boat_dot_v1_dot_pdu__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in boat/v1/pdu_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PduServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendPdu = channel.unary_unary(
                '/boat.v1.PduService/SendPdu',
                request_serializer=boat_dot_v1_dot_pdu__pb2.SendPduRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_pdu__pb2.SendPduResponse.FromString,
                _registered_method=True)
        self.SubscribePdus = channel.unary_stream(
                '/boat.v1.PduService/SubscribePdus',
                request_serializer=boat_dot_v1_dot_pdu__pb2.SubscribePdusRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_pdu__pb2.PduFrame.FromString,
                _registered_method=True)
        self.ConfigureRoute = channel.unary_unary(
                '/boat.v1.PduService/ConfigureRoute',
                request_serializer=boat_dot_v1_dot_pdu__pb2.ConfigureRouteRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_pdu__pb2.ConfigureRouteResponse.FromString,
                _registered_method=True)
        self.ListRoutes = channel.unary_unary(
                '/boat.v1.PduService/ListRoutes',
                request_serializer=boat_dot_v1_dot_pdu__pb2.ListRoutesRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_pdu__pb2.ListRoutesResponse.FromString,
                _registered_method=True)
        self.ConfigureContainer = channel.unary_unary(
                '/boat.v1.PduService/ConfigureContainer',
                request_serializer=boat_dot_v1_dot_pdu__pb2.ConfigureContainerRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_pdu__pb2.ConfigureContainerResponse.FromString,
                _registered_method=True)
        self.ConfigureGroup = channel.unary_unary(
                '/boat.v1.PduService/ConfigureGroup',
                request_serializer=boat_dot_v1_dot_pdu__pb2.ConfigureGroupRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_pdu__pb2.ConfigureGroupResponse.FromString,
                _registered_method=True)
        self.EnableGroup = channel.unary_unary(
                '/boat.v1.PduService/EnableGroup',
                request_serializer=boat_dot_v1_dot_pdu__pb2.EnableGroupRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_pdu__pb2.EnableGroupResponse.FromString,
                _registered_method=True)
        self.DisableGroup = channel.unary_unary(
                '/boat.v1.PduService/DisableGroup',
                request_serializer=boat_dot_v1_dot_pdu__pb2.DisableGroupRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_pdu__pb2.DisableGroupResponse.FromString,
                _registered_method=True)
        self.ListGroups = channel.unary_unary(
                '/boat.v1.PduService/ListGroups',
                request_serializer=boat_dot_v1_dot_pdu__pb2.ListGroupsRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_pdu__pb2.ListGroupsResponse.FromString,
                _registered_method=True)
        self.RemoveRoute = channel.unary_unary(
                '/boat.v1.PduService/RemoveRoute',
                request_serializer=boat_dot_v1_dot_pdu__pb2.RemoveRouteRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_pdu__pb2.RemoveRouteResponse.FromString,
                _registered_method=True)


class PduServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SendPdu(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribePdus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRoutes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PduServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendPdu': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPdu,
                    request_deserializer=boat_dot_v1_dot_pdu__pb2.SendPduRequest.FromString,
                    response_serializer=boat_dot_v1_dot_pdu__pb2.SendPduResponse.SerializeToString,
            ),
            'SubscribePdus': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribePdus,
                    request_deserializer=boat_dot_v1_dot_pdu__pb2.SubscribePdusRequest.FromString,
                    response_serializer=boat_dot_v1_dot_pdu__pb2.PduFrame.SerializeToString,
            ),
            'ConfigureRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureRoute,
                    request_deserializer=boat_dot_v1_dot_pdu__pb2.ConfigureRouteRequest.FromString,
                    response_serializer=boat_dot_v1_dot_pdu__pb2.ConfigureRouteResponse.SerializeToString,
            ),
            'ListRoutes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRoutes,
                    request_deserializer=boat_dot_v1_dot_pdu__pb2.ListRoutesRequest.FromString,
                    response_serializer=boat_dot_v1_dot_pdu__pb2.ListRoutesResponse.SerializeToString,
            ),
            'ConfigureContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureContainer,
                    request_deserializer=boat_dot_v1_dot_pdu__pb2.ConfigureContainerRequest.FromString,
                    response_serializer=boat_dot_v1_dot_pdu__pb2.ConfigureContainerResponse.SerializeToString,
            ),
            'ConfigureGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureGroup,
                    request_deserializer=boat_dot_v1_dot_pdu__pb2.ConfigureGroupRequest.FromString,
                    response_serializer=boat_dot_v1_dot_pdu__pb2.ConfigureGroupResponse.SerializeToString,
            ),
            'EnableGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableGroup,
                    request_deserializer=boat_dot_v1_dot_pdu__pb2.EnableGroupRequest.FromString,
                    response_serializer=boat_dot_v1_dot_pdu__pb2.EnableGroupResponse.SerializeToString,
            ),
            'DisableGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableGroup,
                    request_deserializer=boat_dot_v1_dot_pdu__pb2.DisableGroupRequest.FromString,
                    response_serializer=boat_dot_v1_dot_pdu__pb2.DisableGroupResponse.SerializeToString,
            ),
            'ListGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGroups,
                    request_deserializer=boat_dot_v1_dot_pdu__pb2.ListGroupsRequest.FromString,
                    response_serializer=boat_dot_v1_dot_pdu__pb2.ListGroupsResponse.SerializeToString,
            ),
            'RemoveRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveRoute,
                    request_deserializer=boat_dot_v1_dot_pdu__pb2.RemoveRouteRequest.FromString,
                    response_serializer=boat_dot_v1_dot_pdu__pb2.RemoveRouteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boat.v1.PduService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('boat.v1.PduService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PduService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendPdu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.PduService/SendPdu',
            boat_dot_v1_dot_pdu__pb2.SendPduRequest.SerializeToString,
            boat_dot_v1_dot_pdu__pb2.SendPduResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribePdus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/boat.v1.PduService/SubscribePdus',
            boat_dot_v1_dot_pdu__pb2.SubscribePdusRequest.SerializeToString,
            boat_dot_v1_dot_pdu__pb2.PduFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.PduService/ConfigureRoute',
            boat_dot_v1_dot_pdu__pb2.ConfigureRouteRequest.SerializeToString,
            boat_dot_v1_dot_pdu__pb2.ConfigureRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRoutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.PduService/ListRoutes',
            boat_dot_v1_dot_pdu__pb2.ListRoutesRequest.SerializeToString,
            boat_dot_v1_dot_pdu__pb2.ListRoutesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.PduService/ConfigureContainer',
            boat_dot_v1_dot_pdu__pb2.ConfigureContainerRequest.SerializeToString,
            boat_dot_v1_dot_pdu__pb2.ConfigureContainerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.PduService/ConfigureGroup',
            boat_dot_v1_dot_pdu__pb2.ConfigureGroupRequest.SerializeToString,
            boat_dot_v1_dot_pdu__pb2.ConfigureGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.PduService/EnableGroup',
            boat_dot_v1_dot_pdu__pb2.EnableGroupRequest.SerializeToString,
            boat_dot_v1_dot_pdu__pb2.EnableGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.PduService/DisableGroup',
            boat_dot_v1_dot_pdu__pb2.DisableGroupRequest.SerializeToString,
            boat_dot_v1_dot_pdu__pb2.DisableGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.PduService/ListGroups',
            boat_dot_v1_dot_pdu__pb2.ListGroupsRequest.SerializeToString,
            boat_dot_v1_dot_pdu__pb2.ListGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.PduService/RemoveRoute',
            boat_dot_v1_dot_pdu__pb2.RemoveRouteRequest.SerializeToString,
            boat_dot_v1_dot_pdu__pb2.RemoveRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
