# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: boat/v1/plugin.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'boat/v1/plugin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from boat.v1 import common_pb2 as boat_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62oat/v1/plugin.proto\x12\x07\x62oat.v1\x1a\x14\x62oat/v1/common.proto\"J\n\x06Plugin\x12\x11\n\tplugin_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0e\n\x06loaded\x18\x04 \x01(\x08\":\n\x15RegisterPluginRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x13\n\x0b\x63onfig_json\x18\x02 \x01(\t\">\n\x12ListPluginsRequest\x12(\n\x04page\x18\x01 \x01(\x0b\x32\x1a.boat.v1.PaginationRequest\")\n\x14GetPluginInfoRequest\x12\x11\n\tplugin_id\x18\x01 \x01(\t\"(\n\x13UnloadPluginRequest\x12\x11\n\tplugin_id\x18\x01 \x01(\t\"V\n\x0ePluginResponse\x12\x1f\n\x06plugin\x18\x01 \x01(\x0b\x32\x0f.boat.v1.Plugin\x12#\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x14.boat.v1.ErrorDetail\"b\n\x13ListPluginsResponse\x12 \n\x07plugins\x18\x01 \x03(\x0b\x32\x0f.boat.v1.Plugin\x12)\n\x04page\x18\x02 \x01(\x0b\x32\x1b.boat.v1.PaginationResponse\"M\n\x14UnloadPluginResponse\x12\x10\n\x08unloaded\x18\x01 \x01(\x08\x12#\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x14.boat.v1.ErrorDetail2\xba\x02\n\rPluginService\x12I\n\x0eRegisterPlugin\x12\x1e.boat.v1.RegisterPluginRequest\x1a\x17.boat.v1.PluginResponse\x12H\n\x0bListPlugins\x12\x1b.boat.v1.ListPluginsRequest\x1a\x1c.boat.v1.ListPluginsResponse\x12G\n\rGetPluginInfo\x12\x1d.boat.v1.GetPluginInfoRequest\x1a\x17.boat.v1.PluginResponse\x12K\n\x0cUnloadPlugin\x12\x1c.boat.v1.UnloadPluginRequest\x1a\x1d.boat.v1.UnloadPluginResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'boat.v1.plugin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLUGIN']._serialized_start=55
  _globals['_PLUGIN']._serialized_end=129
  _globals['_REGISTERPLUGINREQUEST']._serialized_start=131
  _globals['_REGISTERPLUGINREQUEST']._serialized_end=189
  _globals['_LISTPLUGINSREQUEST']._serialized_start=191
  _globals['_LISTPLUGINSREQUEST']._serialized_end=253
  _globals['_GETPLUGININFOREQUEST']._serialized_start=255
  _globals['_GETPLUGININFOREQUEST']._serialized_end=296
  _globals['_UNLOADPLUGINREQUEST']._serialized_start=298
  _globals['_UNLOADPLUGINREQUEST']._serialized_end=338
  _globals['_PLUGINRESPONSE']._serialized_start=340
  _globals['_PLUGINRESPONSE']._serialized_end=426
  _globals['_LISTPLUGINSRESPONSE']._serialized_start=428
  _globals['_LISTPLUGINSRESPONSE']._serialized_end=526
  _globals['_UNLOADPLUGINRESPONSE']._serialized_start=528
  _globals['_UNLOADPLUGINRESPONSE']._serialized_end=605
  _globals['_PLUGINSERVICE']._serialized_start=608
  _globals['_PLUGINSERVICE']._serialized_end=922
# @@protoc_insertion_point(module_scope)
