# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from boat.v1 import replay_pb2 as boat_dot_v1_dot_replay__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in boat/v1/replay_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReplayServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartReplay = channel.unary_unary(
                '/boat.v1.ReplayService/StartReplay',
                request_serializer=boat_dot_v1_dot_replay__pb2.StartReplayRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_replay__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.SeekReplay = channel.unary_unary(
                '/boat.v1.ReplayService/SeekReplay',
                request_serializer=boat_dot_v1_dot_replay__pb2.SeekReplayRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_replay__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.StreamReplay = channel.unary_stream(
                '/boat.v1.ReplayService/StreamReplay',
                request_serializer=boat_dot_v1_dot_replay__pb2.StreamReplayRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_replay__pb2.ReplayEvent.FromString,
                _registered_method=True)
        self.PauseReplay = channel.unary_unary(
                '/boat.v1.ReplayService/PauseReplay',
                request_serializer=boat_dot_v1_dot_replay__pb2.PauseReplayRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_replay__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.ResumeReplay = channel.unary_unary(
                '/boat.v1.ReplayService/ResumeReplay',
                request_serializer=boat_dot_v1_dot_replay__pb2.ResumeReplayRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_replay__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.StopReplay = channel.unary_unary(
                '/boat.v1.ReplayService/StopReplay',
                request_serializer=boat_dot_v1_dot_replay__pb2.StopReplayRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_replay__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.ImportTraceData = channel.unary_unary(
                '/boat.v1.ReplayService/ImportTraceData',
                request_serializer=boat_dot_v1_dot_replay__pb2.ImportTraceDataRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_replay__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.StartReplayFromEvents = channel.unary_unary(
                '/boat.v1.ReplayService/StartReplayFromEvents',
                request_serializer=boat_dot_v1_dot_replay__pb2.StartReplayFromEventsRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_replay__pb2.ReplayControlResponse.FromString,
                _registered_method=True)


class ReplayServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StartReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SeekReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportTraceData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartReplayFromEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.StartReplay,
                    request_deserializer=boat_dot_v1_dot_replay__pb2.StartReplayRequest.FromString,
                    response_serializer=boat_dot_v1_dot_replay__pb2.ReplayControlResponse.SerializeToString,
            ),
            'SeekReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.SeekReplay,
                    request_deserializer=boat_dot_v1_dot_replay__pb2.SeekReplayRequest.FromString,
                    response_serializer=boat_dot_v1_dot_replay__pb2.ReplayControlResponse.SerializeToString,
            ),
            'StreamReplay': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamReplay,
                    request_deserializer=boat_dot_v1_dot_replay__pb2.StreamReplayRequest.FromString,
                    response_serializer=boat_dot_v1_dot_replay__pb2.ReplayEvent.SerializeToString,
            ),
            'PauseReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseReplay,
                    request_deserializer=boat_dot_v1_dot_replay__pb2.PauseReplayRequest.FromString,
                    response_serializer=boat_dot_v1_dot_replay__pb2.ReplayControlResponse.SerializeToString,
            ),
            'ResumeReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeReplay,
                    request_deserializer=boat_dot_v1_dot_replay__pb2.ResumeReplayRequest.FromString,
                    response_serializer=boat_dot_v1_dot_replay__pb2.ReplayControlResponse.SerializeToString,
            ),
            'StopReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.StopReplay,
                    request_deserializer=boat_dot_v1_dot_replay__pb2.StopReplayRequest.FromString,
                    response_serializer=boat_dot_v1_dot_replay__pb2.ReplayControlResponse.SerializeToString,
            ),
            'ImportTraceData': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportTraceData,
                    request_deserializer=boat_dot_v1_dot_replay__pb2.ImportTraceDataRequest.FromString,
                    response_serializer=boat_dot_v1_dot_replay__pb2.ReplayControlResponse.SerializeToString,
            ),
            'StartReplayFromEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.StartReplayFromEvents,
                    request_deserializer=boat_dot_v1_dot_replay__pb2.StartReplayFromEventsRequest.FromString,
                    response_serializer=boat_dot_v1_dot_replay__pb2.ReplayControlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boat.v1.ReplayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('boat.v1.ReplayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplayService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.ReplayService/StartReplay',
            boat_dot_v1_dot_replay__pb2.StartReplayRequest.SerializeToString,
            boat_dot_v1_dot_replay__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SeekReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.ReplayService/SeekReplay',
            boat_dot_v1_dot_replay__pb2.SeekReplayRequest.SerializeToString,
            boat_dot_v1_dot_replay__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/boat.v1.ReplayService/StreamReplay',
            boat_dot_v1_dot_replay__pb2.StreamReplayRequest.SerializeToString,
            boat_dot_v1_dot_replay__pb2.ReplayEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.ReplayService/PauseReplay',
            boat_dot_v1_dot_replay__pb2.PauseReplayRequest.SerializeToString,
            boat_dot_v1_dot_replay__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.ReplayService/ResumeReplay',
            boat_dot_v1_dot_replay__pb2.ResumeReplayRequest.SerializeToString,
            boat_dot_v1_dot_replay__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.ReplayService/StopReplay',
            boat_dot_v1_dot_replay__pb2.StopReplayRequest.SerializeToString,
            boat_dot_v1_dot_replay__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportTraceData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.ReplayService/ImportTraceData',
            boat_dot_v1_dot_replay__pb2.ImportTraceDataRequest.SerializeToString,
            boat_dot_v1_dot_replay__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartReplayFromEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.ReplayService/StartReplayFromEvents',
            boat_dot_v1_dot_replay__pb2.StartReplayFromEventsRequest.SerializeToString,
            boat_dot_v1_dot_replay__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
