# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: boat/v1/scenario.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'boat/v1/scenario.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from boat.v1 import common_pb2 as boat_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x62oat/v1/scenario.proto\x12\x07\x62oat.v1\x1a\x14\x62oat/v1/common.proto\">\n\x08Scenario\x12\x13\n\x0bscenario_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"<\n\x15\x43reateScenarioRequest\x12#\n\x08scenario\x18\x01 \x01(\x0b\x32\x11.boat.v1.Scenario\")\n\x12GetScenarioRequest\x12\x13\n\x0bscenario_id\x18\x01 \x01(\t\"@\n\x14ListScenariosRequest\x12(\n\x04page\x18\x01 \x01(\x0b\x32\x1a.boat.v1.PaginationRequest\"*\n\x17ValidateScenarioRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\",\n\x15\x44\x65leteScenarioRequest\x12\x13\n\x0bscenario_id\x18\x01 \x01(\t\"\\\n\x10ScenarioResponse\x12#\n\x08scenario\x18\x01 \x01(\x0b\x32\x11.boat.v1.Scenario\x12#\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x14.boat.v1.ErrorDetail\"h\n\x15ListScenariosResponse\x12$\n\tscenarios\x18\x01 \x03(\x0b\x32\x11.boat.v1.Scenario\x12)\n\x04page\x18\x02 \x01(\x0b\x32\x1b.boat.v1.PaginationResponse\"9\n\x18ValidateScenarioResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0e\n\x06issues\x18\x02 \x03(\t\"N\n\x16\x44\x65leteScenarioResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x12#\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x14.boat.v1.ErrorDetail2\xa1\x03\n\x0fScenarioService\x12K\n\x0e\x43reateScenario\x12\x1e.boat.v1.CreateScenarioRequest\x1a\x19.boat.v1.ScenarioResponse\x12\x45\n\x0bGetScenario\x12\x1b.boat.v1.GetScenarioRequest\x1a\x19.boat.v1.ScenarioResponse\x12N\n\rListScenarios\x12\x1d.boat.v1.ListScenariosRequest\x1a\x1e.boat.v1.ListScenariosResponse\x12W\n\x10ValidateScenario\x12 .boat.v1.ValidateScenarioRequest\x1a!.boat.v1.ValidateScenarioResponse\x12Q\n\x0e\x44\x65leteScenario\x12\x1e.boat.v1.DeleteScenarioRequest\x1a\x1f.boat.v1.DeleteScenarioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'boat.v1.scenario_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENARIO']._serialized_start=57
  _globals['_SCENARIO']._serialized_end=119
  _globals['_CREATESCENARIOREQUEST']._serialized_start=121
  _globals['_CREATESCENARIOREQUEST']._serialized_end=181
  _globals['_GETSCENARIOREQUEST']._serialized_start=183
  _globals['_GETSCENARIOREQUEST']._serialized_end=224
  _globals['_LISTSCENARIOSREQUEST']._serialized_start=226
  _globals['_LISTSCENARIOSREQUEST']._serialized_end=290
  _globals['_VALIDATESCENARIOREQUEST']._serialized_start=292
  _globals['_VALIDATESCENARIOREQUEST']._serialized_end=334
  _globals['_DELETESCENARIOREQUEST']._serialized_start=336
  _globals['_DELETESCENARIOREQUEST']._serialized_end=380
  _globals['_SCENARIORESPONSE']._serialized_start=382
  _globals['_SCENARIORESPONSE']._serialized_end=474
  _globals['_LISTSCENARIOSRESPONSE']._serialized_start=476
  _globals['_LISTSCENARIOSRESPONSE']._serialized_end=580
  _globals['_VALIDATESCENARIORESPONSE']._serialized_start=582
  _globals['_VALIDATESCENARIORESPONSE']._serialized_end=639
  _globals['_DELETESCENARIORESPONSE']._serialized_start=641
  _globals['_DELETESCENARIORESPONSE']._serialized_end=719
  _globals['_SCENARIOSERVICE']._serialized_start=722
  _globals['_SCENARIOSERVICE']._serialized_end=1139
# @@protoc_insertion_point(module_scope)
