# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from boat.v1 import scenario_pb2 as boat_dot_v1_dot_scenario__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in boat/v1/scenario_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScenarioServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateScenario = channel.unary_unary(
                '/boat.v1.ScenarioService/CreateScenario',
                request_serializer=boat_dot_v1_dot_scenario__pb2.CreateScenarioRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_scenario__pb2.ScenarioResponse.FromString,
                _registered_method=True)
        self.GetScenario = channel.unary_unary(
                '/boat.v1.ScenarioService/GetScenario',
                request_serializer=boat_dot_v1_dot_scenario__pb2.GetScenarioRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_scenario__pb2.ScenarioResponse.FromString,
                _registered_method=True)
        self.ListScenarios = channel.unary_unary(
                '/boat.v1.ScenarioService/ListScenarios',
                request_serializer=boat_dot_v1_dot_scenario__pb2.ListScenariosRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_scenario__pb2.ListScenariosResponse.FromString,
                _registered_method=True)
        self.ValidateScenario = channel.unary_unary(
                '/boat.v1.ScenarioService/ValidateScenario',
                request_serializer=boat_dot_v1_dot_scenario__pb2.ValidateScenarioRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_scenario__pb2.ValidateScenarioResponse.FromString,
                _registered_method=True)
        self.DeleteScenario = channel.unary_unary(
                '/boat.v1.ScenarioService/DeleteScenario',
                request_serializer=boat_dot_v1_dot_scenario__pb2.DeleteScenarioRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_scenario__pb2.DeleteScenarioResponse.FromString,
                _registered_method=True)


class ScenarioServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateScenario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScenario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListScenarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateScenario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteScenario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScenarioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateScenario,
                    request_deserializer=boat_dot_v1_dot_scenario__pb2.CreateScenarioRequest.FromString,
                    response_serializer=boat_dot_v1_dot_scenario__pb2.ScenarioResponse.SerializeToString,
            ),
            'GetScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScenario,
                    request_deserializer=boat_dot_v1_dot_scenario__pb2.GetScenarioRequest.FromString,
                    response_serializer=boat_dot_v1_dot_scenario__pb2.ScenarioResponse.SerializeToString,
            ),
            'ListScenarios': grpc.unary_unary_rpc_method_handler(
                    servicer.ListScenarios,
                    request_deserializer=boat_dot_v1_dot_scenario__pb2.ListScenariosRequest.FromString,
                    response_serializer=boat_dot_v1_dot_scenario__pb2.ListScenariosResponse.SerializeToString,
            ),
            'ValidateScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateScenario,
                    request_deserializer=boat_dot_v1_dot_scenario__pb2.ValidateScenarioRequest.FromString,
                    response_serializer=boat_dot_v1_dot_scenario__pb2.ValidateScenarioResponse.SerializeToString,
            ),
            'DeleteScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteScenario,
                    request_deserializer=boat_dot_v1_dot_scenario__pb2.DeleteScenarioRequest.FromString,
                    response_serializer=boat_dot_v1_dot_scenario__pb2.DeleteScenarioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boat.v1.ScenarioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('boat.v1.ScenarioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScenarioService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.ScenarioService/CreateScenario',
            boat_dot_v1_dot_scenario__pb2.CreateScenarioRequest.SerializeToString,
            boat_dot_v1_dot_scenario__pb2.ScenarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.ScenarioService/GetScenario',
            boat_dot_v1_dot_scenario__pb2.GetScenarioRequest.SerializeToString,
            boat_dot_v1_dot_scenario__pb2.ScenarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListScenarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.ScenarioService/ListScenarios',
            boat_dot_v1_dot_scenario__pb2.ListScenariosRequest.SerializeToString,
            boat_dot_v1_dot_scenario__pb2.ListScenariosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.ScenarioService/ValidateScenario',
            boat_dot_v1_dot_scenario__pb2.ValidateScenarioRequest.SerializeToString,
            boat_dot_v1_dot_scenario__pb2.ValidateScenarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.ScenarioService/DeleteScenario',
            boat_dot_v1_dot_scenario__pb2.DeleteScenarioRequest.SerializeToString,
            boat_dot_v1_dot_scenario__pb2.DeleteScenarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
