# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: boat/v1/signal.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'boat/v1/signal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from boat.v1 import common_pb2 as boat_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62oat/v1/signal.proto\x12\x07\x62oat.v1\x1a\x14\x62oat/v1/common.proto\"\x8d\x01\n\x0bSignalValue\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04tick\x18\x02 \x01(\x04\x12\x16\n\x0cnumber_value\x18\x03 \x01(\x01H\x00\x12\x13\n\tint_value\x18\x04 \x01(\x03H\x00\x12\x16\n\x0cstring_value\x18\x05 \x01(\tH\x00\x12\x14\n\nbool_value\x18\x06 \x01(\x08H\x00\x42\x07\n\x05value\"R\n\x13InjectSignalRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\x12$\n\x06signal\x18\x02 \x01(\x0b\x32\x14.boat.v1.SignalValue\"?\n\x17SubscribeSignalsRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\x12\r\n\x05names\x18\x02 \x03(\t\"h\n\x17GetSignalHistoryRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12(\n\x04page\x18\x03 \x01(\x0b\x32\x1a.boat.v1.PaginationRequest\"h\n\x15SignalHistoryResponse\x12$\n\x06values\x18\x01 \x03(\x0b\x32\x14.boat.v1.SignalValue\x12)\n\x04page\x18\x02 \x01(\x0b\x32\x1b.boat.v1.PaginationResponse\"M\n\x14InjectSignalResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12#\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x14.boat.v1.ErrorDetail2\x80\x02\n\rSignalService\x12K\n\x0cInjectSignal\x12\x1c.boat.v1.InjectSignalRequest\x1a\x1d.boat.v1.InjectSignalResponse\x12L\n\x10SubscribeSignals\x12 .boat.v1.SubscribeSignalsRequest\x1a\x14.boat.v1.SignalValue0\x01\x12T\n\x10GetSignalHistory\x12 .boat.v1.GetSignalHistoryRequest\x1a\x1e.boat.v1.SignalHistoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'boat.v1.signal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNALVALUE']._serialized_start=56
  _globals['_SIGNALVALUE']._serialized_end=197
  _globals['_INJECTSIGNALREQUEST']._serialized_start=199
  _globals['_INJECTSIGNALREQUEST']._serialized_end=281
  _globals['_SUBSCRIBESIGNALSREQUEST']._serialized_start=283
  _globals['_SUBSCRIBESIGNALSREQUEST']._serialized_end=346
  _globals['_GETSIGNALHISTORYREQUEST']._serialized_start=348
  _globals['_GETSIGNALHISTORYREQUEST']._serialized_end=452
  _globals['_SIGNALHISTORYRESPONSE']._serialized_start=454
  _globals['_SIGNALHISTORYRESPONSE']._serialized_end=558
  _globals['_INJECTSIGNALRESPONSE']._serialized_start=560
  _globals['_INJECTSIGNALRESPONSE']._serialized_end=637
  _globals['_SIGNALSERVICE']._serialized_start=640
  _globals['_SIGNALSERVICE']._serialized_end=896
# @@protoc_insertion_point(module_scope)
