# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from boat.v1 import signal_pb2 as boat_dot_v1_dot_signal__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in boat/v1/signal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SignalServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InjectSignal = channel.unary_unary(
                '/boat.v1.SignalService/InjectSignal',
                request_serializer=boat_dot_v1_dot_signal__pb2.InjectSignalRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_signal__pb2.InjectSignalResponse.FromString,
                _registered_method=True)
        self.SubscribeSignals = channel.unary_stream(
                '/boat.v1.SignalService/SubscribeSignals',
                request_serializer=boat_dot_v1_dot_signal__pb2.SubscribeSignalsRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_signal__pb2.SignalValue.FromString,
                _registered_method=True)
        self.GetSignalHistory = channel.unary_unary(
                '/boat.v1.SignalService/GetSignalHistory',
                request_serializer=boat_dot_v1_dot_signal__pb2.GetSignalHistoryRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_signal__pb2.SignalHistoryResponse.FromString,
                _registered_method=True)


class SignalServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def InjectSignal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeSignals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignalHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InjectSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.InjectSignal,
                    request_deserializer=boat_dot_v1_dot_signal__pb2.InjectSignalRequest.FromString,
                    response_serializer=boat_dot_v1_dot_signal__pb2.InjectSignalResponse.SerializeToString,
            ),
            'SubscribeSignals': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeSignals,
                    request_deserializer=boat_dot_v1_dot_signal__pb2.SubscribeSignalsRequest.FromString,
                    response_serializer=boat_dot_v1_dot_signal__pb2.SignalValue.SerializeToString,
            ),
            'GetSignalHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignalHistory,
                    request_deserializer=boat_dot_v1_dot_signal__pb2.GetSignalHistoryRequest.FromString,
                    response_serializer=boat_dot_v1_dot_signal__pb2.SignalHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boat.v1.SignalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('boat.v1.SignalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SignalService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InjectSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.SignalService/InjectSignal',
            boat_dot_v1_dot_signal__pb2.InjectSignalRequest.SerializeToString,
            boat_dot_v1_dot_signal__pb2.InjectSignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeSignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/boat.v1.SignalService/SubscribeSignals',
            boat_dot_v1_dot_signal__pb2.SubscribeSignalsRequest.SerializeToString,
            boat_dot_v1_dot_signal__pb2.SignalValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignalHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.SignalService/GetSignalHistory',
            boat_dot_v1_dot_signal__pb2.GetSignalHistoryRequest.SerializeToString,
            boat_dot_v1_dot_signal__pb2.SignalHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
