# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from boat.v1 import simulation_pb2 as boat_dot_v1_dot_simulation__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in boat/v1/simulation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimulationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSimulation = channel.unary_unary(
                '/boat.v1.SimulationService/CreateSimulation',
                request_serializer=boat_dot_v1_dot_simulation__pb2.CreateSimulationRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_simulation__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.StartSimulation = channel.unary_unary(
                '/boat.v1.SimulationService/StartSimulation',
                request_serializer=boat_dot_v1_dot_simulation__pb2.StartSimulationRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_simulation__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.PauseSimulation = channel.unary_unary(
                '/boat.v1.SimulationService/PauseSimulation',
                request_serializer=boat_dot_v1_dot_simulation__pb2.PauseSimulationRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_simulation__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.StepSimulation = channel.unary_unary(
                '/boat.v1.SimulationService/StepSimulation',
                request_serializer=boat_dot_v1_dot_simulation__pb2.StepSimulationRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_simulation__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.ResetSimulation = channel.unary_unary(
                '/boat.v1.SimulationService/ResetSimulation',
                request_serializer=boat_dot_v1_dot_simulation__pb2.ResetSimulationRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_simulation__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.StopSimulation = channel.unary_unary(
                '/boat.v1.SimulationService/StopSimulation',
                request_serializer=boat_dot_v1_dot_simulation__pb2.StopSimulationRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_simulation__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.GetSimulationState = channel.unary_unary(
                '/boat.v1.SimulationService/GetSimulationState',
                request_serializer=boat_dot_v1_dot_simulation__pb2.GetSimulationStateRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_simulation__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.WatchSimulation = channel.unary_stream(
                '/boat.v1.SimulationService/WatchSimulation',
                request_serializer=boat_dot_v1_dot_simulation__pb2.GetSimulationStateRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_simulation__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.ListSimulations = channel.unary_unary(
                '/boat.v1.SimulationService/ListSimulations',
                request_serializer=boat_dot_v1_dot_simulation__pb2.ListSimulationsRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_simulation__pb2.ListSimulationsResponse.FromString,
                _registered_method=True)


class SimulationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StepSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSimulationState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSimulations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSimulation,
                    request_deserializer=boat_dot_v1_dot_simulation__pb2.CreateSimulationRequest.FromString,
                    response_serializer=boat_dot_v1_dot_simulation__pb2.SimulationResponse.SerializeToString,
            ),
            'StartSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSimulation,
                    request_deserializer=boat_dot_v1_dot_simulation__pb2.StartSimulationRequest.FromString,
                    response_serializer=boat_dot_v1_dot_simulation__pb2.SimulationResponse.SerializeToString,
            ),
            'PauseSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseSimulation,
                    request_deserializer=boat_dot_v1_dot_simulation__pb2.PauseSimulationRequest.FromString,
                    response_serializer=boat_dot_v1_dot_simulation__pb2.SimulationResponse.SerializeToString,
            ),
            'StepSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.StepSimulation,
                    request_deserializer=boat_dot_v1_dot_simulation__pb2.StepSimulationRequest.FromString,
                    response_serializer=boat_dot_v1_dot_simulation__pb2.SimulationResponse.SerializeToString,
            ),
            'ResetSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetSimulation,
                    request_deserializer=boat_dot_v1_dot_simulation__pb2.ResetSimulationRequest.FromString,
                    response_serializer=boat_dot_v1_dot_simulation__pb2.SimulationResponse.SerializeToString,
            ),
            'StopSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSimulation,
                    request_deserializer=boat_dot_v1_dot_simulation__pb2.StopSimulationRequest.FromString,
                    response_serializer=boat_dot_v1_dot_simulation__pb2.SimulationResponse.SerializeToString,
            ),
            'GetSimulationState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimulationState,
                    request_deserializer=boat_dot_v1_dot_simulation__pb2.GetSimulationStateRequest.FromString,
                    response_serializer=boat_dot_v1_dot_simulation__pb2.SimulationResponse.SerializeToString,
            ),
            'WatchSimulation': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchSimulation,
                    request_deserializer=boat_dot_v1_dot_simulation__pb2.GetSimulationStateRequest.FromString,
                    response_serializer=boat_dot_v1_dot_simulation__pb2.SimulationResponse.SerializeToString,
            ),
            'ListSimulations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSimulations,
                    request_deserializer=boat_dot_v1_dot_simulation__pb2.ListSimulationsRequest.FromString,
                    response_serializer=boat_dot_v1_dot_simulation__pb2.ListSimulationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boat.v1.SimulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('boat.v1.SimulationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimulationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.SimulationService/CreateSimulation',
            boat_dot_v1_dot_simulation__pb2.CreateSimulationRequest.SerializeToString,
            boat_dot_v1_dot_simulation__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.SimulationService/StartSimulation',
            boat_dot_v1_dot_simulation__pb2.StartSimulationRequest.SerializeToString,
            boat_dot_v1_dot_simulation__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.SimulationService/PauseSimulation',
            boat_dot_v1_dot_simulation__pb2.PauseSimulationRequest.SerializeToString,
            boat_dot_v1_dot_simulation__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StepSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.SimulationService/StepSimulation',
            boat_dot_v1_dot_simulation__pb2.StepSimulationRequest.SerializeToString,
            boat_dot_v1_dot_simulation__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.SimulationService/ResetSimulation',
            boat_dot_v1_dot_simulation__pb2.ResetSimulationRequest.SerializeToString,
            boat_dot_v1_dot_simulation__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.SimulationService/StopSimulation',
            boat_dot_v1_dot_simulation__pb2.StopSimulationRequest.SerializeToString,
            boat_dot_v1_dot_simulation__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSimulationState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.SimulationService/GetSimulationState',
            boat_dot_v1_dot_simulation__pb2.GetSimulationStateRequest.SerializeToString,
            boat_dot_v1_dot_simulation__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/boat.v1.SimulationService/WatchSimulation',
            boat_dot_v1_dot_simulation__pb2.GetSimulationStateRequest.SerializeToString,
            boat_dot_v1_dot_simulation__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSimulations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.SimulationService/ListSimulations',
            boat_dot_v1_dot_simulation__pb2.ListSimulationsRequest.SerializeToString,
            boat_dot_v1_dot_simulation__pb2.ListSimulationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
