# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from boat.v1 import trace_pb2 as boat_dot_v1_dot_trace__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in boat/v1/trace_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TraceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTrace = channel.unary_unary(
                '/boat.v1.TraceService/GetTrace',
                request_serializer=boat_dot_v1_dot_trace__pb2.GetTraceRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_trace__pb2.TraceResponse.FromString,
                _registered_method=True)
        self.ListTraces = channel.unary_unary(
                '/boat.v1.TraceService/ListTraces',
                request_serializer=boat_dot_v1_dot_trace__pb2.ListTracesRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_trace__pb2.TraceResponse.FromString,
                _registered_method=True)
        self.StreamTrace = channel.unary_stream(
                '/boat.v1.TraceService/StreamTrace',
                request_serializer=boat_dot_v1_dot_trace__pb2.StreamTraceRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_trace__pb2.TraceEvent.FromString,
                _registered_method=True)
        self.MarkStep = channel.unary_unary(
                '/boat.v1.TraceService/MarkStep',
                request_serializer=boat_dot_v1_dot_trace__pb2.MarkStepRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_trace__pb2.MarkStepResponse.FromString,
                _registered_method=True)


class TraceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetTrace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTraces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTrace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TraceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrace,
                    request_deserializer=boat_dot_v1_dot_trace__pb2.GetTraceRequest.FromString,
                    response_serializer=boat_dot_v1_dot_trace__pb2.TraceResponse.SerializeToString,
            ),
            'ListTraces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTraces,
                    request_deserializer=boat_dot_v1_dot_trace__pb2.ListTracesRequest.FromString,
                    response_serializer=boat_dot_v1_dot_trace__pb2.TraceResponse.SerializeToString,
            ),
            'StreamTrace': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTrace,
                    request_deserializer=boat_dot_v1_dot_trace__pb2.StreamTraceRequest.FromString,
                    response_serializer=boat_dot_v1_dot_trace__pb2.TraceEvent.SerializeToString,
            ),
            'MarkStep': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkStep,
                    request_deserializer=boat_dot_v1_dot_trace__pb2.MarkStepRequest.FromString,
                    response_serializer=boat_dot_v1_dot_trace__pb2.MarkStepResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boat.v1.TraceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('boat.v1.TraceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TraceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.TraceService/GetTrace',
            boat_dot_v1_dot_trace__pb2.GetTraceRequest.SerializeToString,
            boat_dot_v1_dot_trace__pb2.TraceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTraces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.TraceService/ListTraces',
            boat_dot_v1_dot_trace__pb2.ListTracesRequest.SerializeToString,
            boat_dot_v1_dot_trace__pb2.TraceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/boat.v1.TraceService/StreamTrace',
            boat_dot_v1_dot_trace__pb2.StreamTraceRequest.SerializeToString,
            boat_dot_v1_dot_trace__pb2.TraceEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.TraceService/MarkStep',
            boat_dot_v1_dot_trace__pb2.MarkStepRequest.SerializeToString,
            boat_dot_v1_dot_trace__pb2.MarkStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
