# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: boat/v1/trace.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'boat/v1/trace.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from boat.v1 import common_pb2 as boat_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62oat/v1/trace.proto\x12\x07\x62oat.v1\x1a\x14\x62oat/v1/common.proto\"#\n\x0fGetTraceRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\"=\n\x11ListTracesRequest\x12(\n\x04page\x18\x01 \x01(\x0b\x32\x1a.boat.v1.PaginationRequest\"&\n\x12StreamTraceRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\"O\n\nTraceEvent\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x0c\n\x04tick\x18\x02 \x01(\x04\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\t\"_\n\rTraceResponse\x12#\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x13.boat.v1.TraceEvent\x12)\n\x04page\x18\x02 \x01(\x0b\x32\x1b.boat.v1.PaginationResponse\"\xc4\x01\n\x0fMarkStepRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x0f\n\x07step_id\x18\x02 \x01(\r\x12\x11\n\tstep_name\x18\x03 \x01(\t\x12\x10\n\x08sim_tick\x18\x04 \x01(\x04\x12\x38\n\x08metadata\x18\x05 \x03(\x0b\x32&.boat.v1.MarkStepRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"/\n\x10MarkStepResponse\x12\x1b\n\x13marker_timestamp_ns\x18\x01 \x01(\x04\x32\x92\x02\n\x0cTraceService\x12<\n\x08GetTrace\x12\x18.boat.v1.GetTraceRequest\x1a\x16.boat.v1.TraceResponse\x12@\n\nListTraces\x12\x1a.boat.v1.ListTracesRequest\x1a\x16.boat.v1.TraceResponse\x12\x41\n\x0bStreamTrace\x12\x1b.boat.v1.StreamTraceRequest\x1a\x13.boat.v1.TraceEvent0\x01\x12?\n\x08MarkStep\x12\x18.boat.v1.MarkStepRequest\x1a\x19.boat.v1.MarkStepResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'boat.v1.trace_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MARKSTEPREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_MARKSTEPREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_GETTRACEREQUEST']._serialized_start=54
  _globals['_GETTRACEREQUEST']._serialized_end=89
  _globals['_LISTTRACESREQUEST']._serialized_start=91
  _globals['_LISTTRACESREQUEST']._serialized_end=152
  _globals['_STREAMTRACEREQUEST']._serialized_start=154
  _globals['_STREAMTRACEREQUEST']._serialized_end=192
  _globals['_TRACEEVENT']._serialized_start=194
  _globals['_TRACEEVENT']._serialized_end=273
  _globals['_TRACERESPONSE']._serialized_start=275
  _globals['_TRACERESPONSE']._serialized_end=370
  _globals['_MARKSTEPREQUEST']._serialized_start=373
  _globals['_MARKSTEPREQUEST']._serialized_end=569
  _globals['_MARKSTEPREQUEST_METADATAENTRY']._serialized_start=522
  _globals['_MARKSTEPREQUEST_METADATAENTRY']._serialized_end=569
  _globals['_MARKSTEPRESPONSE']._serialized_start=571
  _globals['_MARKSTEPRESPONSE']._serialized_end=618
  _globals['_TRACESERVICE']._serialized_start=621
  _globals['_TRACESERVICE']._serialized_end=895
# @@protoc_insertion_point(module_scope)
